name = "jedi-labs-website"
compatibility_date = "2024-12-04"

[env.production]
routes = [
  { pattern = "*", custom_domain = true }
]

[build]
command = "npm run build"
cwd = "."

[build.upload]
format = "service-worker"
dir = "dist"
main = "./dist/index.html"

[[build.upload.rules]]
type = "ESModule"
globs = ["**/*.js"]

[[build.upload.rules]]
type = "Text"
globs = ["**/*.html"]

[[build.upload.rules]]
type = "Data"
globs = ["**/*"]