name = "jedi-labs-website"
compatibility_date = "2024-12-04"
main = "dist/index.html"

[env.production]
routes = [
  { pattern = "*", custom_domain = true }
]

[build]
command = "npm run build"
cwd = "."

[[rules]]
type = "ESModule"
globs = ["**/*.js"]

[[rules]]
type = "Text"
globs = ["**/*.html"]

[[rules]]
type = "Data"
globs = ["**/*"]